### ISSUE TITLE
VS Code 没有安装

### ISSUE THREAD

**Issue by shrimpPaste** [xianyunleo/EasySrv#28]
当我打开 「编辑hosts」 就会提示 「VSCode没有安装」，可是我是安装了，当我想自己像自己拖动打开的话我也找不到入口。顺便附带每一个tab栏都提示 测试版本，找一个显眼的地方提示就好了。

**Comment by xianyunleo** [comment]
你用的可能是早期的版本，早期的需要注册将VSCode注册到环境变量。新版本不需要，直接安装VSCode，就能使用。
测试版本是有提示，你可以自己编译最新的版本，或者联系我付费服务，没有这个提示。
