### ISSUE TITLE
1.1.5 arm64版本，无法安装PHP

### ISSUE THREAD

**Issue by nooldey** [xianyunleo/EasySrv#51]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/13229398/226801649-ac576108-79fb-4e48-98b9-c42bb46409d7.png">

<img width="880" alt="image" src="https://user-images.githubusercontent.com/13229398/226801718-20d9acdd-06e3-4457-a637-b8fc72e4a313.png">

<img width="268" alt="image" src="https://user-images.githubusercontent.com/13229398/226801761-a4a4adc1-28e9-4d73-b3b0-ff4c272775af.png">

已经清理所有相关文件，并重启电脑后重新安装，依然有问题。

**Comment by xianyunleo** [comment]
Mac 1.1.5版本有bug，
需要先安装1.0.5后，打开初始化完成后，再安装1.1.5版本
