### ISSUE TITLE
win10 ltsc 1809 闪退

### ISSUE THREAD

**Issue by shang-zhen** [xianyunleo/EasySrv#56]
版本：1.3.4
如题，使用的绿色版和安装版都有这个问题。路径么有空格和中文。。

**Comment by xianyunleo** [comment]
方法1：通过快捷方式添加 --no-sandbox 启动
方法2：通过源码重新编译，在目录 ./src/main/index.js 末尾增加app.commandLine.appendSwitch('--no-sandbox')

**Comment by xianyunleo** [comment]
方法1：通过快捷方式添加 --no-sandbox 启动
方法2：通过源码重新编译，在目录 ./src/main/index.js 末尾增加app.commandLine.appendSwitch('--no-sandbox')

此问题下个版本修复
