### ISSUE TITLE
软件第一次安装的时候无法修改mysql密码，需要拆卸后再次安装才可以

### ISSUE THREAD

**Issue by shang-zhen** [xianyunleo/EasySrv#60]
如题~~~~~~

**Comment by xianyunleo** [comment]
你的系统和EasySrv版本是什么？

**Comment by shang-zhen** [comment]
> 你的系统和EasySrv版本是什么？@shang-zhen
**win10 ltsc 2019**

 另外mac下软件商店安装php报错：


`配置出错，初始化PHP配置失败！ENOENT: no such file or directory, lstat '/Applications/EasySrv/software/php/php-7.1/php.ini-development'`

**Comment by xianyunleo** [comment]
@shang-zhen  你说的两个问题都已解决，请卸载完整后，安装v1.5.7再试

**Comment by shang-zhen** [comment]
> @shang-zhen 你说的两个问题都已解决，请卸载完整后，安装v1.5.7再试
初始化报错🤔
![截屏2023-05-19 14 18 11](https://github.com/xianyunleo/EasySrv/assets/12292101/693f3186-169b-474d-b12f-86b092e44735)

**Comment by xianyunleo** [comment]
1.初始化mysql报错。已修复。
2.composer环境变量已修复。
3.自带编辑软件改了提示。没做提示选择打开方式。

@shang-zhen 请卸载完整后，安装v1.5.9再试

**Comment by shang-zhen** [comment]
ok，辛苦啦。软件安装的时候能不能先判断本地是否有缓存文件（比如MD5判断下是否相同？），如果有的话就不用下载，这样也不用浪费服务器流量。
