### ISSUE TITLE
fpm是不是有些问题？无法访问代理后的网页内容

### ISSUE THREAD

**Issue by shang-zhen** [xianyunleo/EasySrv#62]
测试环境：win10  1.5.9版
比如如下测试代码：
```
// 目标 URL
$url = 'https://medium.com/';

$opts = array('http' => array('proxy' => 'tcp://127.0.0.1:10809', 'request_fulluri' => true));
$context = stream_context_create($opts);

$data = file_get_contents($url, false, $context);

echo $data;
```

命令行直接访问：` ./php.exe D:\work\web\markdown\testv.php` 正常输出
如果用软件新建站点，然后打开这个文件则无法正常输出（一直加载中...）

**Comment by xianyunleo** [comment]
@shang-zhen ，不懂这个 ，你换其他Windows环境试试。

**Comment by shang-zhen** [comment]
@xianyunleo 
不知道怎么回事呢 其他环境没这种问题，idea中设置php目录为EasySrv的PHP目录，直接预览也没问题..
就是创建站点后不行

**Comment by xianyunleo** [comment]
@shang-zhen 你自己研究一下吧。

**Comment by xianyunleo** [comment]
@shang-zhen 可能是 php-cgi-spawner.exe（FPM）不行或者php-cgi.exe不行。你自己研究一下吧。

**Comment by shang-zhen** [comment]
@xianyunleo 奇怪，换了个php版本又可以了😄
