### ISSUE TITLE
编译环境

### ISSUE THREAD

**Issue by MutouRenMe** [xianyunleo/EasySrv#63]
能不能简要说明一下编译环境要求和编译打包的方法
想尝试自己新增和修改一下功能，目前yarn安装没有成功

**Comment by xianyunleo** [comment]
本项目使用的是npm。编译相关的问题，不提供任何帮助。

**Comment by xianyunleo** [comment]
本项目使用的是npm。编译相关的问题，由于本人繁忙，不提供帮助。

**Comment by MutouRenMe** [comment]
不用提供太详细的说明
简单说明一下编译环境这些就行了
比如node版本，所需的软件版本
谢谢！

**Comment by xianyunleo** [comment]
node v16
