### ISSUE TITLE
安装软件太慢了- -...有啥办法提速吗?还有PHP安装扩展能否增加一些

### ISSUE THREAD

**Issue by isszz** [xianyunleo/EasySrv#71]
imagick啥的吧

**Comment by isszz** [comment]
建议把软件列表操作按钮, 安装和卸载放在前面, 把管理放在后面, 这样就不会像下面这样看起来有点乱的感觉了- -
![8fac247d37b2880d5aa99b93baa833fa](https://github.com/xianyunleo/EasySrv/assets/2878463/094af961-f5d3-43b0-af6c-7ac2de767394)

**Comment by isszz** [comment]
每秒下载几KB- -。。。时间太久失败了。。。
![image](https://github.com/xianyunleo/EasySrv/assets/2878463/48e5eac0-4f5d-48ad-af10-5e9490cec884)

**Comment by xianyunleo** [comment]
成本原因，服务器在美国。至于扩展，后续会慢慢加
