### ISSUE TITLE
无法写 hosts

### ISSUE THREAD

**Issue by tint** [xianyunleo/EasySrv#86]
![image](https://github.com/xianyunleo/EasySrv/assets/46518383/d8a020c4-8a7b-4667-8db4-2f8f94aabcda)
![image](https://github.com/xianyunleo/EasySrv/assets/46518383/2799ce27-87d2-47e4-9f20-da7cec49272b)

**Comment by xianyunleo** [comment]
自己手动修改hosts文件的权限

**Comment by xianyunleo** [comment]
请自行检查并修改hosts文件的权限
